.TH LSX 1 dmenu\-VERSION
.SH NAME
lsx \- list executables
.SH SYNOPSIS
.B lsx
.RB [ \-v ]
.RI [ directory ...]
.SH DESCRIPTION
.B lsx
lists the executables in each directory. If no directories are given the current
working directory is used.
.SH OPTIONS
.TP
.B \-v
prints version information to stdout, then exits.
